config/routes.rb
Judge::Application.routes.draw do

  resources :languages
  resources :groups

  root :to => "static_pages#home"

  resources :submissions do
      collection do
          get :downloadInput
          get :pending
          put :jupload
      end
      member do
        get :judgebot
        get :bot_testcase
        get :update_veredict
        put :jdownload
      end
  end

  resources :users do
    collection do
      post :sign_in
      get :sign_out
    end
  end

  resources :problems do
      resources :testcases do
      end
  end

  match 'listexercises' => 'exercises#getvalid'
  match 'listgroups' => 'groups#list_groups'
  match 'admin' => 'static_pages#admin'
  match 'info' => 'static_pages#info'
  match 'exercise/:id' => 'exercises#exercise'
  resources :exercises do
      resources :exercise_problems do
        member do
          get :download
          get :rejudge
        end
      end
      member do
        post :add_group
        get :rem_group
      end
  end

  resources :groups do
      member do
        post :add_user , :add_exer , :add_user_confirm
        get :rem_user , :rem_exer
      end
  end

  resources :exercises do
    member do
      post :add_user
    end
  end

  resources :users do
      member do
        post :add_group
        get :rem_group
      end
  end

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  attr_accessible :name, :notes
  attr_accessible :checker, :pdescription

  validates_presence_of :name


  has_attached_file :pdescription, :path => ":rails_root/protected/problems/:basename:id.:extension", :default_url => 'ndesc.pdf'
  has_attached_file :checker, :path => ':rails_root/protected/checkers/:basename:id.:extension' , :default_url => 'checker.cpp'
  validates_attachment_size :pdescription, :less_than => 2.megabytes
  validates_attachment_size :checker, :less_than => 2.megabytes

  has_many :exercise_problems ,  :dependent => :destroy
  has_many :exercises, :through=>:exercise_problems
  has_many :testcases,  :dependent => :destroy
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_filter :req_psetter
  before_filter :init_vars

  def init_vars
    @user = current_user
  end

  # GET /problems
  # GET /problems.json
  def index
    @search = Problem.search(params[:q])
    @problems = @search.result.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @problems }
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = Problem.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @problem }
    end
  end

  # GET /problems/1/edit
  def edit
    @problem = Problem.find(params[:id])
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(params[:problem])

    respond_to do |format|
      if @problem.save
        flash[:class] = "alert alert-success"
        format.html { redirect_to @problem, :notice => 'Problem was successfully created.' }
        format.json { render :json => @problem, :status => :created, :location => @problem }
      else
        format.html { render :action => "new" }
        format.json { render :json => @problem.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    @problem = Problem.find(params[:id])

    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        flash[:class] = "alert alert-success"
        format.html { redirect_to @problem, :notice => 'Problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @problem.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_form.html.erb
<%= form_for @problem, :html => { :class => 'form-horizontal', :multipart=>true } do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">

      <h3 class="text-error">The problem can't be create</h3>
      <h4 class="text-error"> <%= pluralize(@problem.errors.count, "error") %> </h4>
      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li class="text-error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :pdescription, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :pdescription, :class => 'file_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :notes, :class => 'text_area' %>
    </div>
  </div>


  <div class="control-group">
    <%= f.label :checker, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :checker %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                problems_path, :class => 'btn' %>
  </div>
<% end %>

app/views/problems/_problem.html.erb
<dl class="dl-horizontal">
  <dd> <h2><%= @problem.name %></h2> </dd>
  <dd>  <%= @problem.pdescription.url %> </dd>
  <dd><%= raw(@problem.notes) %></dd>
</dl>

app/views/problems/edit.html.erb
<%- model_class = Problem -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/problems/index.html.erb
<%- model_class = Problem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= search_form_for @search do |f| %>
  <div class="field">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont %>
  </div>
  <div class="actions">
    <%= f.submit "Seach" %>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th>Checker lang</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= link_to problem.id, problem_path(problem) %></td>
        <td><%= problem.name %></td>
        <td><%= problem.pdescription.url %></td>
        <td><%=l problem.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_problem_path(problem), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      problem_path(problem),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>

  <%= will_paginate @posts %>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_problem_path,
            :class => 'btn btn-primary' %>

app/views/problems/new.html.erb
<%- model_class = Problem -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/problems/show.html.erb
<%- model_class = Problem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<%= render @problem %>

<%  if @user and @user.has_roles(User.roles[:psetter]) then %> 
  <hr class="bs-docs-separator"> 
  <h3>Test cases: </h3>
  <%= render "testcases/index" %>
  <h3>Add new test case: </h3>
  <%= render "testcases/form" %>
  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                problems_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_problem_path(@problem), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                problem_path(@problem),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </div>
<% end %>