config/routes.rb
Judge::Application.routes.draw do

  resources :languages
  resources :groups

  root :to => "static_pages#home"

  resources :submissions do
      collection do
          get :downloadInput
          get :pending
          put :jupload
      end
      member do
        get :judgebot
        get :bot_testcase
        get :update_veredict
        put :jdownload
      end
  end

  resources :users do
    collection do
      post :sign_in
      get :sign_out
    end
  end

  resources :problems do
      resources :testcases do
      end
  end

  match 'listexercises' => 'exercises#getvalid'
  match 'listgroups' => 'groups#list_groups'
  match 'admin' => 'static_pages#admin'
  match 'info' => 'static_pages#info'
  match 'exercise/:id' => 'exercises#exercise'
  resources :exercises do
      resources :exercise_problems do
        member do
          get :download
          get :rejudge
        end
      end
      member do
        post :add_group
        get :rem_group
      end
  end

  resources :groups do
      member do
        post :add_user , :add_exer , :add_user_confirm
        get :rem_user , :rem_exer
      end
  end

  resources :exercises do
    member do
      post :add_user
    end
  end

  resources :users do
      member do
        post :add_group
        get :rem_group
      end
  end

end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :compilation, :execution, :ltype, :name, :extension
  has_many :submissions
  #ltype: is compiled(1) or interpreted(2)?
  #name: Human friendly name
  #execution and compilation: lines to execute and compile the code with uppercase keywords to be
  # replaced by the actual filenames

end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  before_filter :req_root

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all

    respond_to do |format|
      format.html # index.html.erb
#      format.json { render json: @languages }
    end
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
    @language = Language.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
#      format.json { render json: @language }
    end
  end

  # GET /languages/new
  # GET /languages/new.json
  def new
    @language = Language.new

    respond_to do |format|
      format.html # new.html.erb
#      format.json { render json: @language }
    end
  end

  # GET /languages/1/edit
  def edit
    @language = Language.find(params[:id])
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(params[:language])

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
#        format.json { render json: @language, status: :created, location: @language }
      else
        format.html { render action: "new" }
#        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /languages/1
  # PUT /languages/1.json
  def update
    @language = Language.find(params[:id])

    respond_to do |format|
      if @language.update_attributes(params[:language])
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
#        format.json { head :no_content }
      else
        format.html { render action: "edit" }
#        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language = Language.find(params[:id])
    @language.destroy

    respond_to do |format|
      format.html { redirect_to languages_url }
#      format.json { head :no_content }
    end
  end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_for(@language) do |f| %>
  <% if @language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% @language.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ltype %><br />
    <%= f.select :ltype, [['Compiled',1],['Interpreted',2]] %>
  </div>
  <div class="field">
    <%= f.label :extension %><br />
    <%= f.text_field :extension %>
  </div>
  <div class="field">
    <%= f.label :compilation %><br />
    <%= f.text_field :compilation %>
  </div>
  <div class="field">
    <%= f.label :execution %><br />
    <%= f.text_field :execution %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing language</h1>

<%= render 'form' %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<h1>Listing languages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Ltype</th>
    <th>Extension</th>
    <th>Compilation</th>
    <th>Execution</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @languages.each do |language| %>
  <tr>
    <td><%= language.name %></td>
    <td><b><%= language.ltype %></b></td>
    <td><b><%= language.extension %></b></td>
    <td><pre><%= language.compilation %></pre></td>
    <td><pre><%= language.execution %></pre></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_language_path(language), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      language_path(language),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>

  </tr>
<% end %>
</table>

<br />

<%= link_to t('.new', :default => t("helpers.links.new")),
              new_language_path,
            :class => 'btn btn-primary' %>

app/views/languages/new.html.erb
<h1>New language</h1>

<%= render 'form' %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @language.name %>
</p>

<p>
  <b>Ltype:</b>
  <%= @language.ltype %>
</p>

<p>
  <b>Extension:</b>
  <%= @language.extension %>
  </p>

<p>
  <b>Compilation:</b>
  <pre> <%= @language.compilation %> </pre>
</p>

<p>
  <b>Execution:</b>
  <pre> <%= @language.execution %> </pre>
</p>


<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>