config/routes.rb
Judge::Application.routes.draw do

  resources :languages
  resources :groups

  root :to => "static_pages#home"

  resources :submissions do
      collection do
          get :downloadInput
          get :pending
          put :jupload
      end
      member do
        get :judgebot
        get :bot_testcase
        get :update_veredict
        put :jdownload
      end
  end

  resources :users do
    collection do
      post :sign_in
      get :sign_out
    end
  end

  resources :problems do
      resources :testcases do
      end
  end

  match 'listexercises' => 'exercises#getvalid'
  match 'listgroups' => 'groups#list_groups'
  match 'admin' => 'static_pages#admin'
  match 'info' => 'static_pages#info'
  match 'exercise/:id' => 'exercises#exercise'
  resources :exercises do
      resources :exercise_problems do
        member do
          get :download
          get :rejudge
        end
      end
      member do
        post :add_group
        get :rem_group
      end
  end

  resources :groups do
      member do
        post :add_user , :add_exer , :add_user_confirm
        get :rem_user , :rem_exer
      end
  end

  resources :exercises do
    member do
      post :add_user
    end
  end

  resources :users do
      member do
        post :add_group
        get :rem_group
      end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :owner, :password
  
  has_and_belongs_to_many :users
  has_and_belongs_to_many :exercises
  
  validates_uniqueness_of :name
  
  def owner_name
    return User.find(owner).name
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :req_psetter, :except=> [ :index,:list_groups , :add_user_confirm]
  before_filter :req_root, :only=>:index
  before_filter :match_user, :except => [:index, :new, :create,:list_groups , :add_user_confirm]

  def match_user(group=nil)
    if(group==nil)
      group = Group.find(params[:id])
    end
    auth = @current_user && @current_user.id==group.owner
    return unauthorized_user unless auth
    return true
  end

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
#      format.json { render json: @groups }
    end
  end

  def list_groups
    @groups = Group.all
    respond_to do |format|
      format.html # list_groups.html.erb
#      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @users = User.all
    @exercises = Exercise.all

    respond_to do |format|
      format.html # show.html.erb
#      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
#      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
    return unless match_user(@group)
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    @group.owner = @current_user.id

    respond_to do |format|
      if @group.save
        flash[:class] = "alert alert-success"
        @group.users << @current_user
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
#        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
#        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    return unless match_user(@group)

    respond_to do |format|
      if @group.update_attributes(params[:group])
        flash[:class] = "alert alert-success"
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
#        format.json { head :no_content }
      else
        format.html { render action: "edit" }
#        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_user_confirm
    @group = Group.find(params[:id])
    user = User.find(params[:user])
    pssw = params[:pwd];

    if(@group.password == pssw)
      if !@group.users.where(:id => user.id).first
        @group.users << user
        render :text => "The user wass successfully added to this group"
      else
        render :text => 'That user is already in this group'
      end
    else
        render :text => "The password doesn't match"
    end

  end

  def add_user
    @group = Group.find(params[:id])
    user = User.find(params[:user])
    if !@group.users.where(:id => user.id).first
      @group.users << user
      flash[:class] = "alert alert-success"
      redirect_to @group, :notice => 'User was successfully added to this group'
    else
      redirect_to @user, :notice => 'That user is already in this group'
    end
  end

  def rem_user
  	@group = Group.find(params[:id])
    user = User.find(params[:user])
    @group.users.delete(user)
    flash[:class] = "alert alert-success"
    redirect_to @group, :notice => 'User was successfully deleted from this group'
  end

  def add_exer
    @group = Group.find(params[:id])
    exercise = Exercise.find(params[:exercise])
    @group.exercises << exercise
    flash[:class] = "alert alert-success"
    redirect_to @group, :notice => 'Exercise was successfully added to this group'
  end

  def rem_exer
  	@group = Group.find(params[:id])
    exercise = Exercise.find(params[:exercise])
    @group.exercises.delete(exercise)
    flash[:class] = "alert alert-success"
    redirect_to @group, :notice => 'Exercise was successfully deleted from this group'
  end


  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    #return unless match_user(@group)
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
#      format.json { head :no_content }
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_exercise.html.erb
<%= form_tag({:controller => "groups", :action => "add_exer"}, :method => "post") do %>
    Exercises:
    <%= select_tag "exercise", options_from_collection_for_select(@exercises, "id", "name") %>
    <%= submit_tag("Add exercise") %>
<% end %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Exercise id</th>
      <th>Exercise name </th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @group.exercises.each do |exercise| %>
      <tr>
        <td><%= link_to exercise.id, exercise_path(exercise) %></td>
        <td><%= exercise.name %></td>
        <td>
        <%= link_to "delete",:controller => "groups", :action => "rem_exer" , :exercise => exercise.id%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal' } do |f| %>

  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h3 class="text-error">The exercise can't be create</h3>
      <h4 class="text-error"> <%= pluralize(@group.errors.count, "error") %> </h4>
      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li class="text-error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'text_field' %>
    </div>
  </div>
      
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                groups_path, :class => 'btn' %>
  </div>
<% end %>

app/views/groups/_form2.html.erb
<p>algoo</p>

app/views/groups/_user.html.erb
<%= form_tag({:controller => "groups", :action => "add_user"}, :method => "post") do %>
    Users:
    <%= select_tag "user", options_from_collection_for_select(@users, "id", "name") %>
    <%= submit_tag("Add user") %>
<% end %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>User id</th>
      <th>User name </th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @group.users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td>
        <%= link_to "delete",:controller => "groups", :action => "rem_user" , :user => user.id%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:owner) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.id, group_path(group) %></td>
        <td><%= group.name %></td>
        <td><%= group.password %></td>
        <td><%= group.owner %></td>
        <td><%=l group.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_group_path(group), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_path(group),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_path,
            :class => 'btn btn-primary' %>

app/views/groups/list_groups.html.erb
<%- model_class = Group -%>


<script type="text/javascript">
  $(document).ready(function(){
      $("#register").click(function(e){
          e.preventDefault();
          var password = prompt("Please enter your password, Harry Potter ?");
          
          if (password != null){
               var group = $("input[name=command]:checked").val();
               //alert(group + " : " + password);
               var uurl = "/groups/"+group+"/add_user_confirm/";
             
               var id;
               <% if @current_user %>
                  id = <%= @current_user.id %>;
               <%else%>
                  id= -1;
               <%end%>
               /*$.post(uurl , { id: group , user: id  , pwd: password })
               .done(function(data) {
                alert("todo bien: " + data);
               })
               .beforeSend(function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))});*/
               $.ajax({ url: uurl,
                  type: 'POST',
                  beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                  data: { id: group , user: id  , pwd: password },
                  success: function(response) {
                    alert(response);
                  }
                });
            
          }
      });
  });
</script>






<div class="page-header">
  <h1>List of groups to register</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:owner) %></th>
    </tr>
  </thead>
  
  <tbody>
  <fieldset data-role="controlgroup" data-type="vertical" id="comandos" >
      <% @groups.each do |group| %>
          <tr>
            <td> <label for="command"><input data-inline="true" type="radio" class="controller" name="command" 
            value= "<%= group.id %>" >  <%= group.name %> </label> </td>
            <td><%= group.owner %></td>
          </tr>
      <% end %>
        
  </fieldset>
  </tbody>

    
</table>

<button class="btn btn-small btn-success" type="button" id="register">Register</button>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/show.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @group.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @group.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:owner) %>:</strong></dt>
  <dd><%= @group.owner_name %></dd>
</dl>

<hr class="bs-docs-separator">
<h3>Users of this group</h3>
<%= render "user" %>
<hr class="bs-docs-separator">
<h3>Exercises of this group</h3>
<%= render "exercise" %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              groups_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_group_path(@group), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              group_path(@group),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>