config/routes.rb
Judge::Application.routes.draw do

  resources :languages
  resources :groups

  root :to => "static_pages#home"

  resources :submissions do
      collection do
          get :downloadInput
          get :pending
          put :jupload
      end
      member do
        get :judgebot
        get :bot_testcase
        get :update_veredict
        put :jdownload
      end
  end

  resources :users do
    collection do
      post :sign_in
      get :sign_out
    end
  end

  resources :problems do
      resources :testcases do
      end
  end

  match 'listexercises' => 'exercises#getvalid'
  match 'listgroups' => 'groups#list_groups'
  match 'admin' => 'static_pages#admin'
  match 'info' => 'static_pages#info'
  match 'exercise/:id' => 'exercises#exercise'
  resources :exercises do
      resources :exercise_problems do
        member do
          get :download
          get :rejudge
        end
      end
      member do
        post :add_group
        get :rem_group
      end
  end

  resources :groups do
      member do
        post :add_user , :add_exer , :add_user_confirm
        get :rem_user , :rem_exer
      end
  end

  resources :exercises do
    member do
      post :add_user
    end
  end

  resources :users do
      member do
        post :add_group
        get :rem_group
      end
  end

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :exercise_problem
  belongs_to :user
  belongs_to :testcase
  belongs_to :language

  attr_accessible :end_date, :init_date, :time, :srcfile, :outfile, :infile
  #attr_accessor :language_id
  has_attached_file :srcfile, :path => ":rails_root/protected/submissions/s:basename:id.:extension", :url => "s:basename:id.:extension"
  has_attached_file :outfile, :path => ":rails_root/protected/submissions/o:basename:id.:extension", :url => "o:basename:id.:extension"

  #validates_attachment_presence :src_file
  validates_attachment_size :srcfile, :less_than => 1.megabytes
  validates_attachment_size :outfile, :less_than => 20.megabytes
  #validates_attachment_content_type :srcfile, :content_type => /\A/
  #validates_attachment_content_type :outfile, :content_type => /\A/

  def self.newJudgeDownload(exercise_problem)
    s = Submission.new
    s.init_date = Time.now.to_s(:db)
    s.exercise_problem = exercise_problem
    s.veredict = 'TL'
    testcases = exercise_problem.problem.testcases.where(:jtype => exercise_problem.stype)
    s.testcase = testcases.first
    return s
  end

    ## Code to judge uploadSource
  def self.newJudgeSource(exercise_problem)
    s = Submission.new
    s.init_date = Time.now.to_s(:db)
    s.exercise_problem = exercise_problem
    s.veredict = 'Judging'
    testcases = exercise_problem.problem.testcases.where(:jtype => exercise_problem.stype)
    s.testcase = testcases.first
    return s
  end

  def veredict=(v)
    if v
      write_attribute(:veredict, v.delete("\n"))
    end
  end

  def veredict
    read_attribute(:veredict)
  end

  def judge()
      #If you change this constants, also change Testcase
      self.veredict = "Judging"
      h = Testcase.judgeTypeHash
      tc = self.testcase
      jt = h[tc.jtype]
      if jt == :downloadInput
        judgeDownload(tc)
      else
        judgeUpload(tc)
      end
      save
  end

  def file_exist? (fpath)
      return fpath && FileTest.exists?(fpath)
  end

  def judgeDownload(tc)
      ofile1 = tc.outfile.path
      ofile2 = outfile.path
      self.time = self.end_date - self.init_date
      if self.time > self.exercise_problem.time_limit
        self.veredict = 'TL'
      else
            if file_exist? ofile2
                s = %x{bash djudge.sh #{ofile1} #{ofile2}}
                self.veredict = s.split.last
            end
      end
  end

  def judgeUpload(tc)
    lan = self.language
    exp = self.exercise_problem
    timl = exp.prog_limit
    meml = exp.mem_lim
    ofile = tc.outfile.path
    ifile = tc.infile.path
    sfile = srcfile.path

    comp = lan.compilation.gsub("SOURCE","Main")
    exec = lan.execution.gsub("SOURCE","Main").gsub("-tTL","-t"+timl.to_s).gsub("ML",meml.to_s).gsub("INFILE","Main.in")
    #tl = timl
    #ml = meml
    type = lan.ltype
    self.veredict = "Judging"

    if file_exist? sfile
       #Tell server that a new submission arrived
      require 'socket'
      #s = TCPSocket.new 'localhost', 3010
      subm = self.id.to_s
      #s.puts subm
      #s.close
      #s = %x{sudo -u utpjudjail /home/insilico/utpjudge/judge/sjudge.sh #{sfile} #{ifile} #{ofile} #{type} '#{comp}' '#{exec}' #{timl} #{meml}}
            #self.veredict = s
      #save
    end
  end

  def source
      srcf = srcfile.path
      if file_exist? srcf
          s = File.open(srcf).read
          return "The source code has non UTF8 characters" if not s.is_utf8?
          return s
      end
      return "No source code"
  end

  def get_test_cases
    tc = self.testcase
    in_file = tc.infile.path
    out_file = tc.outfile.path
    if (file_exist? in_file) && (file_exist? out_file)
      return [File.open(in_file).read, File.open(out_file).read]
    else
      return "Error: Could not find output and input files"
    end
  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_filter :req_psetter, :only=>[:destroy,:update,:edit]
  before_filter :req_gen_user, :except=>[:destroy,:update,:edit,:judgebot,:bot_testcase,:update_veredict,:pending]
  http_basic_authenticate_with :name => "user", :password => "password", :only => [:judgebot,:bot_testcase,:update_veredict,:pending]

  # GET /submissions
  # GET /submissions.json
  def index
    u_id = params[:uid]
    if (!u_id || Integer(u_id)!=@current_user.id)
      authorized = @current_user.has_roles(User.roles[:psetter])
      redirect_to :root and return if not authorized
    end
    if u_id
      @submissions = User.find(u_id).submissions.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')
    else
      @submissions = Submission.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @submissions }
    end
  end


  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @submission = Submission.find(params[:id])
    is_authorized = @current_user.id == @submission.user.id || @current_user.has_roles(User.roles[:psetter])
    redirect_to :root and return if not is_authorized

    #if (@submission.veredict == "Judging" || @submission.veredict.length == 0)
      #@submission.judge
    #end
    @exercise_problem = @submission.exercise_problem
    @srccode = @submission.source

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @submission }
      format.xml { render xml: @submission }
    end
  end

  #GET /submissions/1/judgebot.json (Called by judge)
  # Download the submission identified by the given ID (params[:id])
  def judgebot
      @submission = Submission.find(params[:id])
      @srccode = @submission.source
      @lang = @submission.language
      fname = @submission.exercise_problem.problem.checker.path

      if( fname == nil )
          fname = "protected/checkers/checker.cpp"
      end

      tmp = File.open(fname,'r')
      @checker = tmp.read
      @chlang  = fname.split('.')[-1]

      respond_to do |format|
          format.json { render json: [@submission,@srccode,@lang,@submission.exercise_problem, @checker, @chlang] }
      end
  end

  #GET /submissions/1/bot_testcase.json (Called by judge)
  # Used to download testcases by the judgebot
  def bot_testcase
      @submission = Submission.find(params[:id])

      respond_to do |format|
          format.json { render json: @submission.get_test_cases }
      end
  end

  #GET /submissions/pending.json
  def pending
      @pend_ids = Submission.where(:veredict => 'Judging').pluck(:id)
      respond_to do |format|
          format.json { render json: @pend_ids }
      end
  end

  #POST receive the veredict from judbot
  def update_veredict
    @submission = Submission.find(params[:id])
    time = params[:time]
    sub_id    = params[:id]
    veredict  = params[:veredict]

    @submission.veredict = veredict
    @submission.time = time

    respond_to do |format|
      format.json { render json: [veredict] }
    end

    #update on DB
    @submission.update_attributes(params[:submission])

  end

  # GET /submissions/new
  def new
      @exercise_problem = ExerciseProblem.find(params[:exercise_problem])
      @jtype = Testcase.judgeTypeHash[@exercise_problem.stype]
#     flash.now[:notice] = @jtype

      if @jtype==:downloadInput
        @submission = Submission.newJudgeDownload(@exercise_problem)
        @submission.user = current_user
        @submission.save
        render "jdownload"
      else
        @language = Language.all
        @submission = Submission.newJudgeSource(@exercise_problem)
#        @submission.user = current_user
#        @submission.save
        render "jupload"
      end

  end

  def jdownload
     @submission = Submission.find(params[:id])
     @submission.end_date = Time.now.to_s(:db)

     if @submission.user.valid_exercise? @submission.exercise_problem.exercise
        respond_to do |format|
          if @submission.update_attributes(params[:submission]) && @submission.judge
            #if success redirect to show action
            flash[:class] = "alert alert-success"
            format.html { redirect_to @submission, notice: 'Your submission was successfully sent.' }
            format.json { head :no_content }
          else
            format.html { render action: "new" }
            format.json { render json: @submission.errors, status: :unprocessable_entity }
          end
        end
      else
        redirect_to :root, :notice => "You can't do this submission because this exercise is not avaible for you"
      end
  end

  def jupload
    @exercise_problem = ExerciseProblem.find(params[:exercise_problem_id])
    @submission = Submission.newJudgeSource(@exercise_problem)
    @submission.language = Language.find(params[:language_id])
    @submission.end_date = Time.now.to_s(:db)
    @submission.user = current_user
    @submission.save

    if( params[:srcfile] == nil )
      srcpaste = params[:srcpaste];
      if( srcpaste.length > 0 )
        fname = "/tmp/#{@submission.exercise_problem.problem.name[0]}.#{@submission.language.extension}"
        f = File.open(fname,'w')
        f.write(srcpaste)
        f.close
        @submission.srcfile = File.open(fname,'r')
        @submission.save
      end
    end

    respond_to do |format|
      if @submission.update_attributes(params[:submission]) && @submission.judge
        #if success redirect to show action
        flash[:class] = "alert alert-success"
        format.html { redirect_to @submission, notice: 'Your submission was successfully sent.' }
        format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  #GET /submissions/downloadInput?exercise_problem=id
  def downloadInput
      @exercise_problem = ExerciseProblem.find(params[:exercise_problem])
      problem = @exercise_problem.problem
      testcase = problem.testcases.where(:jtype => @exercise_problem.stype).first
      send_file testcase.infile.path, :type=>"application/text"
  end

  # GET /submissions/1/edit
  def edit
    @submission = Submission.find(params[:id])
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(params[:submission])

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render json: @submission, status: :created, location: @submission }
      else
        format.html { render action: "new" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /submissions/1
  # PUT /submissions/1.json
  def update
    @submission = Submission.find(params[:id])

    @submission.veredict = params[:veredict]
    respond_to do |format|
      if @submission.update_attributes(params[:submission])
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_for(@submission) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h3 class="text-error"><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h3>

      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li class="text-error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :init_date %><br />
    <%= f.datetime_select :init_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :veredict %><br />
    <%= text_field_tag :veredict,@submission.veredict %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<%- model_class = Submission -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>User</th>
            <th>Exercise</th>
            <th>Problem</th>
            <th>Time</th>
            <th>Veredict</th>
            <th><%=t '.actions', :default => t("helper.actions") %></th>
        </tr>
    </thead>
    <tbody>
    
    

<% @submissions.each do |submission| %>
    <tr>
        <td><%= link_to submission.id, submission_path(submission) %></td>
        <td><%= link_to submission.user.name, user_path(submission.user) %></td>
        <td><%= submission.exercise_problem.exercise.name %></td>
        <td><%= submission.exercise_problem.problem.name %></td>
        <td><%= submission.time %></td>
        <% if submission.veredict == "Judging" %>
            <td> Pending </td>
        <% else %>
            <td><%= submission.veredict %></td>
        <% end %>
        <td>
          <% if @current_user.has_roles(User.roles[:psetter]) %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      submission_path(submission),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>    
    </tr>   

<% end %>

<%= will_paginate @posts %>

</table>

<br />

app/views/submissions/jdownload.html.erb
<h2>Submit solution</h2>
<%= form_for(@submission, :url=> {:action => "jdownload", :id=>@submission.id}, :html => {:method=>"put", :onsubmit => "return validate_form()"}) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
      <%= f.label :outfile, :class=>'control-label' %>
      <div class="controls">
          <%= f.file_field :outfile %>
      </div>
  </div>

  <div class="control-group">
      <%= f.label :srcfile, :class=>'control-label' %>
      <div class="controls">
          <%= f.file_field :srcfile %>
      </div>
  </div>

  <div class="actions">
      <%= link_to "Download Input", {:controller=>"submissions",:action=>"downloadInput", 
          :exercise_problem=>@exercise_problem.id},{:class => 'btn btn-primary',:target => "blank"} %>
      <%= f.submit :class => 'btn btn-success', :value => 'Submit solution' %>
  </div>

  <div class="control-group">
      Time limit: 
      <div class="controls" id="countdown"></div>
  </div>
<% end %>

<script language="jscript">
    var timer,time;

    window.onload=function(){init_timer()};

    function init_timer() {
        time = <%= @exercise_problem.time_limit %>;
        idSubm = <%= @submission.id %>;
        time_trigger();
    }

    function time_trigger() {
        document.getElementById("countdown").innerHTML=time + " s";
        time--;
        if (time==0) {
            window.location.href="/submissions/"+idSubm;
        }
        timer = setTimeout('time_trigger()',1000);
    }

    function filled(str) {
        return str!=null && str!="";
    }

    function validate_form() {
        var srcfile = document.getElementById("submission_srcfile");
        var outfile = document.getElementById("submission_outfile");
        var v = filled(srcfile.value) && filled(outfile.value);
        if (!v) alert("Both source file and output file must be filled");
        return v;
    }
</script>

app/views/submissions/jupload.html.erb
<h2>Submit solution</h2>
<%= form_for(@submission, :url=> {:action => "jupload", :exercise_problem_id => @exercise_problem.id}, :html => { :class => 'form-horizontal', :multipart=>true, :method=>"put", :onsubmit => "return validate_form()"}) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="control-group">
		<%= f.label :language, :class=>'control-label' %>
    <div class="controls">
			<%= select_tag :language_id, options_from_collection_for_select(@language,:id,:name) %>
    </div>
  </div>

  <div id="editor"><%= "" %></div>
  <script src="http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
  <script type="text/javascript">
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/tomorrow_night");
    editor.getSession().setMode("ace/mode/c_cpp");
  </script>

  <div class="control-group">
      <%= f.label :srcfile, :class=>'control-label' %>
      <div class="controls">
          <%= f.file_field :srcfile %>
      </div>
  </div>

  <%= hidden_field_tag(:srcpaste) %>

  <div class="actions">
      <%= f.submit :class => 'btn btn-success', :value => 'Submit solution' %>
  </div>

<% end %>

<script type="text/javascript">
    function filled(str) {
      return str!=null && str!="";
    }

    function validate_form() {
      var srcfile = document.getElementById("submission_srcfile");
      srcpaste.value = editor.getValue();
      var v = filled(srcfile.value);
      var vv = filled(srcpaste.value);

      if (!v && !vv ) alert("The source file must be filled");
      return v || vv;
    }
</script>

app/views/submissions/new.html.erb
<h1>New submission</h1>
<%= render 'jdownload' if @jtype == :downloadInput %>
<%= render 'jupload' if @jtype == :uploadSource %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<p id="notice"><%= notice %></p>

<dl class="dl-horizontal">
  <dt><strong>User code:</strong></dt>
  <dd><%= @submission.user.code %></dd>
  <dt><strong>User name:</strong></dt>
  <dd><%= @submission.user.name %></dd>
  <dt><strong>Exercise:</strong></dt>
  <dd><%= @submission.exercise_problem.exercise.name %></dd>
  <dt><strong>Problem:</strong></dt>
  <dd><%= @submission.exercise_problem.problem.name %></dd>
  <dt><strong>Veredict:</strong></dt>
  <dd><%= @submission.veredict %></dd>
  <dt><strong>Time:</strong></dt>
  <dd><%= @submission.time %></dd>
  <dt><strong>Init Date:</strong></dt>
  <dd><%= @submission.init_date %></dd>
  <dt><strong>End date:</strong></dt>
  <dd><%= @submission.end_date %></dd>
</dl>


<div id="editor"><%= @srccode %></div>
    
<script src="http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/tomorrow_night");
    editor.getSession().setMode("ace/mode/c_cpp");
</script>




<div class="form-actions">
<% if @current_user.has_roles(User.roles[:psetter]) %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              submissions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_submission_path(@submission), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              submission_path(@submission),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>
<%= link_to t('.b2',:default => t("Back to exercise")),[@exercise_problem.exercise, @exercise_problem], :class=>'btn btn-primary' %> 
</div>